name: instagram_clone
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.8
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  firebase_database: ^9.1.4
  firebase_storage: ^10.3.8
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  flutterfire_ui: ^0.4.3+9
  image_picker: ^0.8.5+3
  path: ^1.8.2
  path_provider: ^2.0.11
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/avatar.jpg
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/billabong.ttf
          # - asset: fonts/Schyler-Italic.ttf
          # style: italic
    - family: SfPro
      fonts:
        - asset: assets/fonts/sfpro/sf_pro.ttf
        - asset: assets/fonts/sfpro/sf_pro_bold.ttf
          style: normal
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
